#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = purge ]; then
    update-desktop-database -q /usr/share/applications 2>/dev/null || true
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor 2>/dev/null || true
fi

if [ "$1" = purge ]; then
    rm -rf /opt/espanso-gui 2>/dev/null || true
fi

